// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCMWebApp.Shared.Models
{
    public partial class Banner
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? BannerTypeId { get; set; }
        public int? ProgrammeId { get; set; }

        public virtual BannerType BannerType { get; set; }
        public virtual Programme Programme { get; set; }
    }
}