// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCMWebApp.Shared.Models
{
    public partial class BannerType
    {
        public BannerType()
        {
            Banner = new HashSet<Banner>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Banner> Banner { get; set; }
    }
}